### ISSUE TITLE
建议优化网址匹配

### ISSUE THREAD

**Issue by ghost** [Valkierja/UJS_jiaoPing#2]
在直连的时候（非webVPN） 并不能触发该插件

**Comment by KSroido** [comment]
了解

**Comment by KSroido** [comment]
跟进中

**Comment by KSroido** [comment]
我这边一般使用VPN连接，不太清楚校内网直连地址，你可以提一个PR我来merge

**Comment by ghost** [comment]
我不会写插件捏
但是直连网址大概长这样的
`http://xuanke*.ujs.edu.cn/(********************)/xsjxpj2_2.aspx?*********************`

**Comment by KSroido** [comment]
> 我不会写插件捏 但是直连网址大概长这样的 `http://xuanke*.ujs.edu.cn/(********************)/xsjxpj2_2.aspx?*********************`

了解,最近考试,之后搞

**Comment by KSroido** [comment]
已跟进, 应当已经解决, 下学期教评时进行QA测试
