### ISSUE TITLE
更新请求

### ISSUE THREAD

**Issue by gongfuture** [Valkierja/UJS_jiaoPing#3]
新版完全变化了，好像用不了了：（

**Comment by gongfuture** [comment]
那一段随机hash好像是有规律的，我自己看了下好像是分三段的，但是我是js纯萌新，自己改了一下，能改value，但是没法提交，希望大佬回坑完善一下

**Comment by KSroido** [comment]
收到, 可以开PR

**Comment by KSroido** [comment]
你可以直接开一个branch, 我给你权限吧

**Comment by KSroido** [comment]
已经基本完成 还有一个小bug 查看dev分支
